### ISSUE TITLE
Post: Open Source SOC

### ISSUE THREAD

**Issue by sroberts** [sroberts/sroberts.github.io#112]
- FIR
- CRITs
- GRR
- etc

**Comment by sroberts** [comment]
Elastalert
Cuckoo Sandbox

**Comment by krmaxwell** [comment]
_bro_

**Comment by sroberts** [comment]
![pasted_image_4_25_15__16_44](https://cloud.githubusercontent.com/assets/44774/7334761/8990c688-eb6a-11e4-9b7e-4ad2ed6e3464.png)

**Comment by krmaxwell** [comment]
Oh and this is probably where MozDef finally fits too (depending on how exhaustive you intend to go with it)

**Comment by sroberts** [comment]
I think you could go towards Elastalert or Mozdef, I could definitely talk the the pros and cons of each.
