### ISSUE TITLE
Post: Threat Intel vs Hunt

### ISSUE THREAD

**Issue by sroberts** [sroberts/sroberts.github.io#113]
This is a half formed idea, but the thought is that "Threat Intel" is a vendor function. Most organizations really want an intel driven IR team (Hunt team).

**Comment by krmaxwell** [comment]
Hrm. I think threat intel takes a lot of external inputs but still can be internally-directed. Doing something with it,, though, that's the IR function (hunting).

**Comment by sroberts** [comment]
I'm talking about "Threat Intel" with a goal of just producing "intel".

**Comment by sroberts** [comment]
Maybe for super large companies you could consider having a separate business function for this, but those are rare.

**Comment by sroberts** [comment]
https://pen-testing.sans.org/resources/papers/gcih/automated-defense-threat-intelligence-augment-121748

**Comment by sroberts** [comment]
Closed in #124
