### ISSUE TITLE
InfoSec Domains

### ISSUE THREAD

**Issue by sroberts** [sroberts/sroberts.github.io#126]
I often think about dividing IR/TI by domains (yes @krmaxwell, in the military domain). I reference this a lot, but it wouldn't be bad to explore it.
## Domains
- Host
- Network
- Environment

**Comment by krmaxwell** [comment]
'Domain' is a perfectly cromulent word.

**Comment by sroberts** [comment]
What can I say, it's military word. [Economist: Warfare in the 5th Domain](http://www.economist.com/node/16478792)

**Comment by krmaxwell** [comment]
In all seriousness, I don't think of it as a military word. To me, it's actually a math term, but in reality I don't think there's a military connotation except the one you have in your head because you're a nerd.

**Comment by sroberts** [comment]
Vaguely taken on. NOt worht considering further.
