### ISSUE TITLE
Add Deep Linking Support

### ISSUE THREAD

**Issue by sroberts** [sroberts/sroberts.github.io#139]
http://ben.balter.com/2014/03/13/pages-anchor-links/

Too many good ideas from @benbalter.

**Comment by sroberts** [comment]
http://bryanbraun.github.io/anchorjs/#basic-usage

**Comment by benbalter** [comment]
To note, I updated the article, just use AnchorJS.

**Comment by sroberts** [comment]
Yeah I saw, hence the link to AnchorJS. I just need to do this sometime.

**Comment by sroberts** [comment]
Added this long ago.
