### ISSUE TITLE
Consider Adding Comments with Disqus

### ISSUE THREAD

**Issue by sroberts** [sroberts/sroberts.github.io#142]
I'm back to wondering about this again. Should be worth considering. Would welcome feedback on this!

**Comment by krmaxwell** [comment]
I am considering comments again, but I'm currently leaning towards just linking to a GitHub issue (possibly the one that drove the initial post so I don't have to create more issues).

**Comment by sroberts** [comment]
That's an interesting idea as well. What I dislike about that is I have to focus on the moderation/spam issues more than with something like Disqus, but I could go either way on that.

**Comment by sroberts** [comment]
Unnecessary due to #265.
