### ISSUE TITLE
Add RSS

### ISSUE THREAD

**Issue by sroberts** [sroberts/sroberts.github.io#144]
https://github.com/tokkonopapa/jekyll-experiment/blob/master/rss.xml

**Comment by krmaxwell** [comment]
https://github.com/krmaxwell/krmaxwell.github.io/blob/master/feed.xml

**Comment by sroberts** [comment]
Does that generate both RSS & Atom? I have Atom already, debating if i also need RSS or not?

**Comment by krmaxwell** [comment]
it's just Atom - not sure you really need both though.

**Comment by sroberts** [comment]
Yeah, not worried really, just a thought.

**Comment by sroberts** [comment]
Officially not bothering.
