### ISSUE TITLE
Introduction to DFIR

### ISSUE THREAD

**Issue by sroberts** [sroberts/sroberts.github.io#180]
- Hard Skills
  - Forensics (Dead disk and memory)
  - Malware Triage
  - Intel/Attacker Methods
  - Development
- Soft Skills
  - Report Writing
  - Presentations
  - Oral Communication
  - People Management

@krmaxwell What am I missing?

**Comment by krmaxwell** [comment]
Network forensics, maybe?

**Comment by sroberts** [comment]
@krmaxwell: Good idea. I'd probably add OSINT as well.

**Comment by krmaxwell** [comment]
AND OPSEC

**Comment by sroberts** [comment]
@krmaxwell: Truth! PREACH BROTHER MAXWELL!

**Comment by krmaxwell** [comment]
In seriousness, though, I'd also think about analytic stuff (e.g. confirmation biases & the like) plus maybe interview skills depending on what they're into. I had to do a bit of that back in my corporate DFIR days.

**Comment by sroberts** [comment]
@krmaxwell Investigative process is one of the most key things, but honestly hardest to talk about/link to. I've had to give that a lot of thought and I'm still not sure.

**Comment by sroberts** [comment]
Useful article: http://waxy.org/2015/12/the_joy_of_getting_hacked/

Useful book: http://www.goodreads.com/book/show/18154.The_Cuckoo_s_Egg

**Comment by sroberts** [comment]
http://motherboard.vice.com/read/cybersecurity-researchers-are-hunted-from-all-sides
