### ISSUE TITLE
Indirect vs Direct Attribution

### ISSUE THREAD

**Issue by sroberts** [sroberts/sroberts.github.io#74]
Putting a name with a face is hard, but putting a name with actions is far easier and just as useful.

**Comment by christiancyint** [comment]
Rob Lee has a good post on this topic: http://www.robertmlee.org/the-problems-with-seeking-and-avoiding-true-attribution-to-cyber-attacks/.

**Comment by sroberts** [comment]
@christiancyint Rob Lee is a far smarter person than I, but I'll definitely use this reference. Thanks for the suggestions!
