### ISSUE TITLE
Enhancment Ideas

### ISSUE THREAD

**Issue by sroberts** [sroberts/sroberts.github.io#97]
- http://erjjones.github.io/blog/How-I-built-my-blog-in-one-day/
- Contact Form: http://www.jotform.com/ 
- http://pixelcog.com/blog/2013/jekyll-from-scratch-extending-jekyll/
- http://sachachua.com/blog/2014/12/making-personal-blogs-useful-people/

**Comment by krmaxwell** [comment]
The :octocat: specific stuff in that first one is :+1: . I have become less of a fan of lots of widgets that clutter up a site.

**Comment by sroberts** [comment]
Yeah I'm not a fan of a lot of cruft but I feel like I'm missing things.

**Comment by sroberts** [comment]
Unnecessary due to #265.
